version: '3.8'

services:
  php:
    image: php:8.5-cli
    container_name: xataface-php85
    working_dir: /app
    volumes:
      - .:/app
    command: tail -f /dev/null
    environment:
      - PHP_VERSION=8.5

  web:
    image: php:8.5-apache
    container_name: xataface-web
    working_dir: /var/www/html
    ports:
      - "8085:80"
    volumes:
      - .:/var/www/html
    environment:
      - PHP_VERSION=8.5
